apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: core-svc-6733
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/core-svc-6733
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
